name: app_todo
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.3.0
  firebase_auth: ^3.3.8
  firebase_storage: ^10.2.8
  cloud_firestore: ^3.1.5
  google_sign_in: ^5.0.3
  dio: ^4.0.0
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.2
  json_annotation: ^4.0.1
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  

flutter:

  uses-material-design: true


